### ISSUE TITLE
TypeError: github_action_helper_1.Logger is not a constructor

### ISSUE THREAD

**Issue by single-stop-tony** [technote-space/assign-author#204]
## Describe the bug: バグの概要
I'm getting the following error when the Assign Author workflow runs on new pull requests. Just started about an hour ago.

```
Run technote-space/assign-author@v1
TypeError: github_action_helper_1.Logger is not a constructor
    at /home/runner/work/_actions/technote-space/assign-author/v1/lib/main.js:20:20
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/technote-space/assign-author/v1/lib/main.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/_actions/technote-space/assign-author/v1/lib/main.js:4:12)
    at run (/home/runner/work/_actions/technote-space/assign-author/v1/lib/main.js:19:19)
    at Object.<anonymous> (/home/runner/work/_actions/technote-space/assign-author/v1/lib/main.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
Error: github_action_helper_1.Logger is not a constructor
```

![Screen Shot 2020-09-25 at 12 12 00 PM](https://user-images.githubusercontent.com/61426305/94290569-5f3f9a80-ff28-11ea-9a48-2fa5b18ff08b.png)

**Comment by technote-space** [comment]
I have fixed this issute. 
Thank you for reporting this.
